<a href="https://colab.research.google.com/github/nialaila24/Kelas-Dasar_PSDS_PD4/blob/main/PSDS_Pertemuan_7__psds_(Pandas_dan_Numpy_Array).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama : Nia Andriani Laila

NIm  : 2000015002

Kelas : DASAR

#Pandas DataFrame

pandas adalah library analisis data yang memiliki struktur data uang diperlukan untuk memebersihkan data mentah ke dalam sebuah bentuk yg cocok untuk analaisis yaitu tabel. 

##Import Modul

In [ ]:
import pandas as pd

## Membuat DataFrame

Membuat Matriks menggunakan list

In [ ]:
#LIst
list_buah = ['Jeruk','Pepaya','Mangga','Rambutan','Leci','Nanas','Manggis']

#Membuat DataFrame dengan list_buah
df = pd.DataFrame(list_buah)
df

0
0     Jeruk
1    Pepaya
2    Mangga
3  Rambutan
4      Leci
5     Nanas
6   Manggis

Membuat Data Frame Menggunakan List dan Fungsi Zip

In [ ]:
#LIst Buah (string)
list_buah = ['Jeruk','Pepaya','Mangga','Rambutan','Leci','Nanas','Manggis']

#List Berat Buah (Integer)
list_berat = [50,800,150,10,2,300,70]

#Membuat DataFrame menggunakan dua buah list dengan fungsi zip
df = pd.DataFrame(list(zip(list_buah, list_berat)),
                  columns = ['Nama Buah', 'Berat Buah'])
df

Nama Buah  Berat Buah
0     Jeruk          50
1    Pepaya         800
2    Mangga         150
3  Rambutan          10
4      Leci           2
5     Nanas         300
6   Manggis          70

Membuat DataFrame Menggunakan List Multidimensi

In [ ]:
#List Multidimensi (Nama,Usia)
list = [['Bejo',25], ['Ari',30], 
        ['Asep',26], ['Richard',22]]

df = pd.DataFrame(list, columns = ['Nama', 'Usia'])
df

Nama  Usia
0     Bejo    25
1      Ari    30
2     Asep    26
3  Richard    22

##Membuat DataFrame Menggunakan Dictionary

In [ ]:
data = 

In [ ]:
mobil = {'Type Mobil': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
         'Harga(USD)': [22000,25000,27000,35000]
         }

df =pd.DataFrame(mobil)
df

Type Mobil  Harga(USD)
0     Honda Civic       22000
1  Toyota Corolla       25000
2      Ford Focus       27000
3         Audi A4       35000

##Import DataFrame dari File CSV

In [ ]:
df_Super_Store = pd.read_csv('Super_Store.csv')
df_Super_Store.head()

NameError: ignored

##Import Data Frame dari File Excel

In [ ]:
df_pilkada=pd.read_excel('datasetpilkadadki.xlsx')
df_pilkada.head()

Id Sentiment Pasangan Calon  \
0   1  negative     Agus-Sylvi   
1   2  negative     Agus-Sylvi   
2   3  negative     Agus-Sylvi   
3   4  negative     Agus-Sylvi   
4   5  negative     Agus-Sylvi   

                                          Text Tweet  
0  Banyak akun kloning seolah2 pendukung #agussil...  
1  #agussilvy bicara apa kasihan yaa...lap itu ai...  
2  Kalau aku sih gak nunggu hasil akhir QC tp lag...  
3  Kasian oh kasian dengan peluru 1milyar untuk t...  
4  Maaf ya pendukung #AgusSilvy..hayo dukung #Ani...

#Numpy Array

Numpy merupakan salah satu library python yang banyak digunakan dalam proses analisis

In [ ]:
import numpy as np

In [ ]:
list_1 = [1,2,3,4,5]
arr_1 = 

In [ ]:
print(np.zeros((2,5))) # membuat array dengan nilai 0 dengan shape (5,5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.ones((5,3))) # membuat array dengan nilai 1 dengan shape (5,5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.arange(1, 10, 2)) # arange(start, stop, step)

[1 3 5 7 9]


In [ ]:
print(np.linspace(1, 10, 2)) # linspace(start, stop, step) artinya menampilkan nilai dalam interval

[ 1. 10.]


In [ ]:
print(np.logspace(1, 10, 2)) # logspace(start, stop, step)

[1.e+01 1.e+10]


In [ ]:
print(np.full((2,2),4)) # membuat array matriks dengan shape (2,2) dengan elemen 99

[[4 4]
 [4 4]]


In [ ]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A, 4)) # membuat array matriks dengan shape yg sama dgn A dgn semua elemen

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [ ]:
print(np.random.rand(4,2)) # Random Decimal Number

[[0.268534   0.39408321]
 [0.36429233 0.72960212]
 [0.06866077 0.6613578 ]
 [0.10730749 0.304053  ]]


In [ ]:
print(np.random.randint(-4,8, size =(3,3))) # Random Integer Values

[[ 3  2  6]
 [-1  2  6]
 [ 7 -1 -3]]


In [ ]:
print(np.identity(5)) # membuat matriks identitas

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3]]) # Membuat matriks dengan perulangan array
r1 = np.repeat(arr,3, axis=0) # axis=0 membuat dalam bentuk kolom
print(r1)


arr = np.array([[1,2,3]]) # Membuat matriks dengan perulangan array
r2 = np.repeat(arr,3, axis=1) # axis=0 membuat dalam bentuk baris
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


##Metode-metode pada Array

Objek array 

In [ ]:
a = np.array([29,28,30], dtype='int32')
print(a)

print("Ukuran Shape dari Array a adalah ", a.ndim)

[29 28 30]
Ukuran Shape dari Array a adalah  1


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

print("Ukuran Shape dari array b adalah ", b.shape)

[[9. 8. 7.]
 [6. 5. 4.]]
Ukuran Shape dari array b adalah  (2, 3)


In [ ]:
a.dtype

dtype('int32')

In [ ]:
a.size

3

In [ ]:
arr_2 = np.array([[1,2,3,4,5], [2,4,6,8,10]])
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [ ]:
arr_2.shape

(2, 5)

In [ ]:
arr_3 = np.array([1,2,3,4,5])
print(arr_3[0])
print(arr_3[2])
print(arr_3[4])

1
3
5


In [ ]:
arr_3 = np.array([1,2,3,4,5])
print(arr_3[0:4])

[1 2 3 4]


Penggabungan DataFrame

In [ ]:
import pandas as pd

Append

Method .append() dapat digunakan pd dataframe yg ditujukan untuk menambahkan row-nya aja

In [ ]:
#Membuat series of int (s1)dan series of string (s2)
s1 = pd.Series([1,2,3,4,5,6])
s2 = pd.Series(["a","b","c",])